Dépôt de mes affiches — Phase V
CUPUM/ecometropole_laurentienne pull request #104
Opened 2022-12-29 17:15 UTC by chloenotte

2022-12-29 17:41 UTC, sjinko reviewed
La demande de traite ne contient qu‘un seul document: notte-affiches-phasev-20221222.jpg

2022-12-29 17:51 UTC, chloenotte commented
Je viens de modifier le dépôt des affiches et le dossier InDesign.

2022-12-29 20:57 UTC, sjinko requested changes
Bonjour,

il faudrait retirer tous les caractères accentués (éêèà) et les cartactères typographiques (.,;'’()) dans le noms de fichier

2022-12-30 18:07 UTC, chloenotte commented
> 

En effet, je viens de corriger le tout à l'instant. Tout devrait être conforme!

2023-01-15 10:46 UTC, sjinko approved these changes

2023-01-15 10:46 UTC, merged